import os
from jinja2 import Template
from weasyprint import HTML, CSS
from datetime import datetime

# A clean, mobile-first, single-column design inspired by The Economist / WSJ apps
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <title>Finance & AI Scout - Daily Report</title>
    <style>
        @page {
            size: A4 portrait;
            margin: 2cm 1.5cm;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, 'Microsoft JhengHei', sans-serif;
            color: #1a1a1a;
            line-height: 1.6;
            background-color: #fcfcfc;
            margin: 0;
            padding: 0;
        }
        .header {
            border-bottom: 4px solid #b30000;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 32px;
            font-weight: 800;
            margin: 0 0 10px 0;
            letter-spacing: -0.5px;
        }
        .header .date {
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .section-title {
            font-size: 24px;
            color: #1a1a1a;
            font-weight: bold;
            text-transform: uppercase;
            border-top: 1px solid #ccc;
            padding-top: 20px;
            margin-top: 40px;
            margin-bottom: 20px;
        }
        .article {
            margin-bottom: 35px;
            page-break-inside: avoid;
        }
        .article-title {
            font-size: 20px;
            font-weight: bold;
            color: #004488;
            margin: 0 0 8px 0;
            line-height: 1.3;
            text-decoration: none;
        }
        .article-meta {
            font-size: 13px;
            color: #777;
            margin-bottom: 12px;
            font-weight: bold;
        }
        .article-summary {
            font-size: 16px;
            color: #333;
            margin-bottom: 15px;
            text-align: justify;
        }
        .social-sentiment {
            background-color: #f1f5f9;
            border-left: 4px solid #3b82f6;
            padding: 12px 15px;
            font-size: 14px;
            color: #1e293b;
            font-style: italic;
            border-radius: 0 4px 4px 0;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 11px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Finance & AI Scout</h1>
        <div class="date">{{ date_str }} | INSIDER BRIEFING</div>
    </div>

    <div class="section-title">Global Financial News</div>
    {% for item in financial_news %}
    <div class="article">
        <a class="article-title" href="{{ item.url }}" target="_blank">{{ item.title }}</a>
        <div class="article-meta">{{ item.source }} | {{ item.date_time }} | <a href="{{ item.url }}" target="_blank" style="color: #0066cc;">閱讀原文 &rarr;</a></div>
        <div class="article-summary">{{ item.summary }}</div>
        {% if item.social_sentiment and item.social_sentiment not in ['目前無顯著社群討論', '待補'] %}
        <div class="social-sentiment">
            <strong>社群風向：</strong>{{ item.social_sentiment }}
        </div>
        {% endif %}
    </div>
    {% endfor %}

    <div class="section-title">Global AI News</div>
    {% for item in ai_news %}
    <div class="article">
        <a class="article-title" href="{{ item.url }}" target="_blank">{{ item.title }}</a>
        <div class="article-meta">{{ item.source }} | {{ item.date_time }} | <a href="{{ item.url }}" target="_blank" style="color: #0066cc;">閱讀原文 &rarr;</a></div>
        <div class="article-summary">{{ item.summary }}</div>
        {% if item.social_sentiment and item.social_sentiment not in ['目前無顯著社群討論', '待補'] %}
        <div class="social-sentiment">
            <strong>社群風向：</strong>{{ item.social_sentiment }}
        </div>
        {% endif %}
    </div>
    {% endfor %}

    <div class="footer">
        Generated by Antigravity AI Agent with Gemini 3.1 Pro & Tavily Search.
    </div>

</body>
</html>
"""

def generate_pdf_report(report_data: dict, output_filepath: str = "daily_report.pdf"):
    """
    Takes the structured report dictionary, fills the Jinja2 HTML template, 
    and converts it to a mobile-friendly PDF using WeasyPrint.
    """
    print("Generating Mobile-friendly PDF report...")
    
    # 1. Render HTML
    template = Template(HTML_TEMPLATE)
    html_content = template.render(
        date_str=datetime.now().strftime("%B %d, %Y"),
        financial_news=report_data.get("global_financial_news", []),
        ai_news=report_data.get("global_ai_news", [])
    )
    
    # 2. Save temporary HTML (optional but good for debugging)
    with open("temp_report.html", "w", encoding="utf-8") as f:
        f.write(html_content)
        
    # 3. Generate PDF
    try:
        HTML(string=html_content).write_pdf(output_filepath)
        print(f"PDF successfully saved to {output_filepath}")
        return output_filepath
    except Exception as e:
        print(f"Failed to generate PDF: {e}")
        return None

if __name__ == "__main__":
    # Test stub
    pass
